sudo: false
language: generic

addons:
  apt:
    packages:
      - libgmp-dev

env:
  matrix:
    - GHCVER=8.2 STACK_YAML=stack-8.2.yaml
    - GHCVER=8.4 STACK_YAML=stack.yaml

install:
  # stack
  - mkdir -p ~/.local/bin
  - travis_retry curl -L https://github.com/commercialhaskell/stack/releases/download/v1.7.1/stack-1.7.1-linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - export PATH=~/.local/bin:$PATH
  - stack --no-terminal --version

script:
  - stack setup --no-terminal
  - stack update --no-terminal
  - stack build -j2 --fast --no-terminal
  - travis_wait 45 sleep 1800 &
  - stack test --fast --no-terminal

after_success:
  - git status
  - if [ -n "$TRAVIS_TAG" ]; then
      echo "Deploying ${TRAVIS_TAG}...";
      stack install --no-terminal;
      mkdir -p deploy && cp ~/.local/bin/b2-cli "./deploy/b2-cli-${TRAVIS_TAG}";
    fi;

cache:
  timeout: 2000
  directories:
  - $HOME/.cabal
  - $HOME/.ghc
  - $HOME/.stack
  - .stack-work/
  apt: true

deploy:
  provider: releases
  file_glob: true
  file: deploy/*
  on:
    tags: true
  api_key:
   secure: "E8ZYLuvb8WJsbW1FUBZ0Q4QnKbpuwJ9VoomWiNueaG1QZ5snsqFlBqa81FnfGXTuXAkIIeHM7epL8B28ausS4ZU1uUQGoovZdrE+2jwruCBulkdanNRmlvTEG1EMgNWTy8NfqKK8NmgLvOq1P9wz22KJ+3uywucuuuTgHQXWzlV1hIEZMsPTXZ3oovDEzYiTJf09jcK7jyYvNkI/wRynq/9aqra0CCLZR5abWEdYoVfCcabAD57O9BQmj/Hbh98pld0UKxN2EJRY+57uSHxa+yqWk6os59Z0iGlIpHy//hQWwel1AVsO2AQCgplph0hLY11hgEPG7tf8icumbuhUJ6hsrm2kjKdfoz2Z01AyYll5KpOskZIGW7aTKEf2eALR5T7+MxYlH6qulw+eNGM6WxsSNVsTsPbAe+RUukYDERDi5Ld2pdSozX2UiZ1bDUwyvVlHe4iCP2kSivIWhQ7PvJAPtAJsIs6PO3JAEk3l3EPHfgmhmom26usZ8kPpEepMYRobdrrqft1Ng3w8flIMD57Fk91HBGuI27emswbJeS6BP/JUYMhfToSXUs4CMUIhK9bJdd0o7PCdEs+wgbKva71dlxf5cZqox6vBYVMqbWwCQgxIT8MJgC1cKfY/PhW9Fx+Dg4fg5X+Ary9hzCw5MwZ88RpBYyd6b0syDi3f8j4="
  skip-cleanup: true
